FROM alpine AS extract
WORKDIR /data
COPY gene_norm_ddb.tar.gz /data/gene_norm_ddb.tar.gz
RUN tar xzf gene_norm_ddb.tar.gz \
    && rm gene_norm_ddb.tar.gz

FROM amazon/dynamodb-local:latest
USER root
COPY --from=extract /data /home/dynamodblocal/dynamodb_local_latest
RUN chmod -R 0755 /home/dynamodblocal/dynamodb_local_latest
EXPOSE 8000
CMD ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/dynamodb_local_latest"]
