name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image and `develop` as `develop` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env: 
  IMAGE_NAME: gene-normalization # TODO: Change variable to your image's name.
  IMAGE_DESCRIPTION: "" # TODO: Add your description here.
  IMAGE_AUTHORS: "" # TODO: Add image authors using the following style Author Name 1 <author1@email.com>, Author Name 2 <author2@email.com>, ... , Author Name n <authorn@email.com> 

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout


      - name: Prepare tags
        id: prep
        run: |

        # Docker Registries
        GHCR_IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}"
        DOCKER_HUB_IMAGE_NAME="${{ github.repository_owner }}/${{ env.IMAGE_NAME }}"

        TAG=""

        if [[ $GITHUB_REF == refs/tags/* ]]; then
            # If this is a tag push, use the tag name (stripping 'refs/tags/')
            TAG=${GITHUB_REF#refs/tags/}
      
            # Remove leading 'v' from tag if present
            if [[ $TAG == v* ]]; then
              TAG=${TAG#v}
            fi
        elif [[ $GITHUB_REF == refs/heads/main ]]; then
          # If this is a push to main, use 'latest'
          TAG="latest"
        else
          # Otherwise, use the branch name, replacing non-alphanumeric characters with underscores
          TAG=$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^a-zA-Z0-9]/_/g')
        fi

        FINAL_TAGS="$GHCR_IMAGE_NAME:$TAG, $DOCKER_HUB_IMAGE_NAME:$TAG"
        echo "tags=${FINAL_TAGS}" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.authors=${{ env.IMAGE_AUTHORS }}
            maintainer=${{ env.IMAGE_AUTHORS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_SVC_ACCOUNT }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to CANCERVARIANTS DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CANCERVARIANTS_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.CANCERVARIANTS_DOCKER_HUB_TOKEN }}

      - name: Build and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          sbom: true
          push: true
          provenance: mode=max
          tags: ${{ steps.prep.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        